# This file was generated by GoReleaser. DO NOT EDIT.
class Removebg < Formula
  desc "Remove image background - 100% automatically"
  homepage "https://www.remove.bg/"
  version "2.0.0"

  if OS.mac?
    url "https://github.com/remove-bg/remove-bg-cli/releases/download/2.0.0/removebg_cli_2.0.0_macos.tar.gz"
    sha256 "a62261e64a70a12da994c364aeaf389d22a457cb12b5fd80d87763603aaef1c2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/remove-bg/remove-bg-cli/releases/download/2.0.0/removebg_cli_2.0.0_linux.tar.gz"
      sha256 "07fcde27e31466632a41eda178735fd7169fe9c6e0ee0159b80ab66e26390370"
    end
  end

  def install
    bin.install "removebg"
  end
end
